# Generated by Django 3.0.5 on 2021-03-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Contact', models.CharField(max_length=122)),
                ('Length', models.CharField(max_length=122)),
                ('Shoulder', models.CharField(max_length=122)),
                ('Chest', models.CharField(max_length=122)),
                ('Sleeves', models.CharField(max_length=122)),
                ('Neck', models.CharField(max_length=122)),
                ('Arm', models.CharField(max_length=122)),
                ('Width', models.CharField(max_length=122)),
                ('Sleevehole', models.CharField(max_length=122)),
                ('Hip', models.CharField(max_length=122)),
                ('Breast', models.CharField(max_length=122)),
                ('Quantity', models.CharField(max_length=122)),
                ('Lengthp', models.CharField(max_length=122)),
                ('Hipp', models.CharField(max_length=122)),
                ('Waist', models.CharField(max_length=122)),
                ('Bottom', models.CharField(max_length=122)),
                ('Knees', models.CharField(max_length=122)),
                ('Calf', models.CharField(max_length=122)),
                ('quantity', models.CharField(max_length=122)),
                ('extra', models.CharField(max_length=122)),
            ],
        ),
        migrations.AlterField(
            model_name='inputs',
            name='fname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputs',
            name='lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
